[build]
buildCommand = "composer install --no-dev --optimize-autoloader && npm install && npm run build && php artisan optimize"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
preDeployCommand = "php artisan migrate --force && php artisan db:seed --force"